In [1]:
import numpy as np

# 一维数组
a = np.arange(10)**3

a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [2]:
# 一维数组的索引

a[2]

8

In [3]:
# 一维数组的切片
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [4]:
# 一维数组的切片, start:stop:step
a[1:8:2]

array([  1,  27, 125, 343], dtype=int32)

In [5]:
# 切片赋值，影响的原始值 (切片返回的是浅拷贝)

a[:6:2] = -1000 
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [6]:
# 倒序
a[ : :-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [7]:
# 遍历一维数组
l = []
for i in a:
    l.append(i**(1/3.))

l

E:\workspace\tdxStock\venv\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in power
  after removing the cwd from sys.path.


[nan,
 1.0,
 nan,
 3.0,
 nan,
 5.0,
 5.999999999999999,
 6.999999999999999,
 7.999999999999999,
 8.999999999999998]

In [8]:
# 多维数组的索引，每个轴可以有一个索引。这些索引以逗号分隔的元组给出

def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [9]:
b[2,3]  # 可以省去元组的括号 b[(2,3)]

23

In [10]:
b[(2,3)]  # 第一轴和第二轴都明确了数值索引，得到的是一个具体的数值

23

In [11]:
# 对于第一轴 选取 0:5 , 对于第二轴选取 1， 得到一维数组
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [12]:
b[ : ,1]

array([ 1, 11, 21, 31, 41])

In [13]:
b[1:3, : ] 

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [14]:
# 当提供的索引少于轴的数量时，缺失的索引被认为是完整的切片:
b[1:3]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [15]:
b[-1]

array([40, 41, 42, 43])

In [16]:
# 三维数组
c = np.array( [[[  0,  1,  2], 
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])
c.shape

(2, 2, 3)

In [17]:
c[1,...]  # ... 省去相邻的 :,:

array([[100, 101, 102],
       [110, 112, 113]])

In [18]:
c[...,2]

array([[  2,  13],
       [102, 113]])

In [19]:
# 对多维数组进行 迭代（Iterating） 是相对于第一个轴完成的
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [20]:
# 但是，如果想要对数组中的每个元素执行操作，可以使用 flat 属性
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [21]:
a = np.arange(12)**2 
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [23]:
# 使用索引数组进行索引
i = np.array( [ 1,1,3,8,5 ] ) 
a[i]

array([ 1,  1,  9, 64, 25], dtype=int32)

In [24]:
j = np.array( [ [ 3, 4], [ 9, 7 ] ] )
a[j] 

array([[ 9, 16],
       [81, 49]], dtype=int32)

In [25]:
palette = np.array( [ [0,0,0],                # black
                      [255,0,0],              # red
                      [0,255,0],              # green
                      [0,0,255],              # blue
                      [255,255,255] ] )       # white
image = np.array( [ [ 0, 1, 2, 0 ],
                    [ 0, 3, 4, 0 ]  ] )

# 当被索引数组 palette 是多维的时，单个索引数组 image 指的是第一个维度
# 这里只索引了第一维
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [26]:
# 还可以为多个维度提供索引，每个维度的索引数组必须具有相同的形状
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
i = np.array( [ [0,1], [1,2] ] )  # 第一维的索引数组
j = np.array( [ [2,1], [3,3] ] )  # 第二维的索引数组

a[i,j]

array([[ 2,  5],
       [ 7, 11]])

In [29]:
a[i,2]

array([[ 2,  6],
       [ 6, 10]])

In [30]:
a[:,j] 

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [31]:
# 使用布尔数组进行索引
a = np.arange(12).reshape(3,4)
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [32]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [33]:
a[b] = 0 
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [34]:
# 使用布尔值进行索引的第二种方法更类似于整数索引; 对于数组的每个维度，我们给出一个1D布尔数组，选择我们想要的切片
a = np.arange(12).reshape(3,4)
b1 = np.array([False,True,True])
b2 = np.array([True,False,True,False])
a[b1,:] 

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
a[:,b2]  

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [36]:
a[b1,b2] 

array([ 4, 10])